const nodemailer = require('nodemailer');
const path = require('path');

// Load .env file from the correct path
require('dotenv').config({ path: path.join(__dirname, '../.env') });

// Environment variables are loaded from .env file

// Environment variables loaded above

// Email configuration function - ensures we get fresh env vars
function getTransporter() {
  const isGmail = (process.env.SMTP_HOST || '').includes('gmail');

  const config = {
    service: isGmail ? 'gmail' : undefined,
    host: isGmail ? undefined : (process.env.SMTP_HOST || 'smtp.gmail.com'),
    port: isGmail ? undefined : (parseInt(process.env.SMTP_PORT) || 587),
    secure: isGmail ? undefined : (process.env.SMTP_PORT === '465'),
    auth: {
      user: process.env.SMTP_USER,
      pass: process.env.SMTP_PASS
    }
  };

  // Add TLS only if not Gmail (Gmail service handles it best)
  if (!isGmail) {
    config.tls = { rejectUnauthorized: false };
  }

  console.log(`📧 Creating transporter [Host: ${process.env.SMTP_HOST}] [User: ${process.env.SMTP_USER}] [Pass Len: ${process.env.SMTP_PASS ? process.env.SMTP_PASS.length : 0}]`);

  return nodemailer.createTransport(config);
}

// Create transporter
const transporter = getTransporter();

// Email templates
const emailTemplates = {
  telecom: {
    subject: 'URGENT: 91 CrPC Notice - Telecom Fraud Case',
    template: (caseData, scammerData) => `
Dear Telecom Regulatory Authority,

This is an automated 91 CrPC notice generated by the FraudLens system for immediate investigation of telecom fraud.

CASE DETAILS:
- Case ID: ${caseData.caseId}
- Victim: ${caseData.user?.name} (${caseData.user?.email})
- Amount Lost: ₹${caseData.amount?.toLocaleString() || '0'}
- Incident Date: ${new Date(caseData.incidentDate).toLocaleDateString()}
- Scammer Phone: ${scammerData?.phoneNumber || 'Not provided'}

VICTIM DETAILS FROM FORM:
- Full Name: ${caseData.formData?.personalInfo?.firstName || ''} ${caseData.formData?.personalInfo?.lastName || ''}
- Phone: ${caseData.formData?.contactInfo?.phone || 'Not provided'}
- Email: ${caseData.formData?.contactInfo?.email || 'Not provided'}
- Address: ${caseData.formData?.addressInfo?.currentAddress?.street || 'Not provided'}, ${caseData.formData?.addressInfo?.currentAddress?.city || ''}, ${caseData.formData?.addressInfo?.currentAddress?.state || ''}
- Aadhaar: ${caseData.formData?.governmentIds?.aadhaarNumber || 'Not provided'}
- PAN: ${caseData.formData?.governmentIds?.panNumber || 'Not provided'}

LEGAL NOTICE:
This notice is issued under Section 91 of the Code of Criminal Procedure, 1973, requiring immediate investigation and action within 48 hours.

Please acknowledge receipt and provide updates on the investigation.

FraudLens System
Cyber Crime Division
    `
  },
  banking: {
    subject: 'URGENT: 91 CrPC Notice - Banking Fraud Case',
    template: (caseData, scammerData) => `
Dear Banking Authority,

This is an automated 91 CrPC notice generated by the FraudLens system for immediate investigation of banking fraud.

CASE DETAILS:
- Case ID: ${caseData.caseId}
- Victim: ${caseData.user?.name} (${caseData.user?.email})
- Amount Lost: ₹${caseData.amount?.toLocaleString() || '0'}
- Incident Date: ${new Date(caseData.incidentDate).toLocaleDateString()}
- Scammer Bank Account: ${scammerData?.bankAccount || 'Not provided'}
- Scammer UPI ID: ${scammerData?.upiId || 'Not provided'}

VICTIM DETAILS FROM FORM:
- Full Name: ${caseData.formData?.personalInfo?.firstName || ''} ${caseData.formData?.personalInfo?.lastName || ''}
- Phone: ${caseData.formData?.contactInfo?.phone || 'Not provided'}
- Email: ${caseData.formData?.contactInfo?.email || 'Not provided'}
- Address: ${caseData.formData?.addressInfo?.currentAddress?.street || 'Not provided'}, ${caseData.formData?.addressInfo?.currentAddress?.city || ''}, ${caseData.formData?.addressInfo?.currentAddress?.state || ''}
- Aadhaar: ${caseData.formData?.governmentIds?.aadhaarNumber || 'Not provided'}
- PAN: ${caseData.formData?.governmentIds?.panNumber || 'Not provided'}

LEGAL NOTICE:
This notice is issued under Section 91 of the Code of Criminal Procedure, 1973, requiring immediate investigation and action within 48 hours.

Please acknowledge receipt and provide updates on the investigation.

FraudLens System
Cyber Crime Division
    `
  },
  nodal: {
    subject: 'URGENT: 91 CrPC Notice - Cyber Crime Case',
    template: (caseData, scammerData) => `
Dear Nodal Officer,

This is an automated 91 CrPC notice generated by the FraudLens system for immediate investigation of cyber crime.

CASE DETAILS:
- Case ID: ${caseData.caseId}
- Victim: ${caseData.user?.name} (${caseData.user?.email})
- Amount Lost: ₹${caseData.amount?.toLocaleString() || '0'}
- Incident Date: ${new Date(caseData.incidentDate).toLocaleDateString()}
- Case Type: ${caseData.caseType}

VICTIM DETAILS FROM FORM:
- Full Name: ${caseData.formData?.personalInfo?.firstName || ''} ${caseData.formData?.personalInfo?.lastName || ''}
- Phone: ${caseData.formData?.contactInfo?.phone || 'Not provided'}
- Email: ${caseData.formData?.contactInfo?.email || 'Not provided'}
- Address: ${caseData.formData?.addressInfo?.currentAddress?.street || 'Not provided'}, ${caseData.formData?.addressInfo?.currentAddress?.city || ''}, ${caseData.formData?.addressInfo?.currentAddress?.state || ''}
- Aadhaar: ${caseData.formData?.governmentIds?.aadhaarNumber || 'Not provided'}
- PAN: ${caseData.formData?.governmentIds?.panNumber || 'Not provided'}

SCAMMER DETAILS:
- Name: ${scammerData?.name || 'Unknown'}
- Phone: ${scammerData?.phoneNumber || 'Not provided'}
- Email: ${scammerData?.email || 'Not provided'}
- UPI ID: ${scammerData?.upiId || 'Not provided'}
- Bank Account: ${scammerData?.bankAccount || 'Not provided'}

LEGAL NOTICE:
This notice is issued under Section 91 of the Code of Criminal Procedure, 1973, requiring immediate investigation and action within 48 hours.

Please acknowledge receipt and provide updates on the investigation.

FraudLens System
Cyber Crime Division
    `
  }
};

// Send email function
async function sendEmail(to, subject, html, attachments = []) {
  try {
    const mailOptions = {
      from: `"FraudLens System" <${process.env.SMTP_USER}>`,
      to: to,
      subject: subject,
      html: html,
      attachments: attachments
    };

    const result = await transporter.sendMail(mailOptions);
    console.log('Email sent successfully:', result.messageId);
    return {
      success: true,
      messageId: result.messageId,
      to: to
    };
  } catch (error) {
    console.error('Email sending failed:', error);
    return {
      success: false,
      error: error.message,
      to: to
    };
  }
}

// Send emails to authorities
async function sendEmailsToAuthorities(caseData, scammerData, recipients) {
  const results = {};

  try {
    // Get email addresses from environment variables with fallbacks
    const telecomEmail = process.env.TELECOM_EMAIL || 'telecom@fraud.gov.in';
    const bankingEmail = process.env.BANKING_EMAIL || 'banking@fraud.gov.in';
    const nodalEmail = process.env.NODAL_EMAIL || 'nodal@fraud.gov.in';

    console.log('📧 Email addresses:');
    console.log('  TELECOM_EMAIL:', telecomEmail);
    console.log('  BANKING_EMAIL:', bankingEmail);
    console.log('  NODAL_EMAIL:', nodalEmail);

    // Send to telecom authority
    if (recipients.telecom) {
      const template = emailTemplates.telecom;
      const subject = template.subject;
      const content = template.template(caseData, scammerData);
      console.log('📧 Sending email to telecom:', telecomEmail);
      try {
        const result = await sendEmail(telecomEmail, subject, content);
        results.telecom = {
          success: result.success,
          messageId: result.messageId,
          to: result.to,
          email: telecomEmail,
          subject,
          content,
          status: result.success ? 'sent' : 'failed',
          error: result.error
        };
      } catch (error) {
        console.error('❌ Telecom email error:', error);
        results.telecom = { success: false, error: error.message, status: 'failed', subject, content };
      }
    }

    // Send to banking authority
    if (recipients.banking) {
      const template = emailTemplates.banking;
      const subject = template.subject;
      const content = template.template(caseData, scammerData);
      console.log('📧 Sending email to banking:', bankingEmail);
      try {
        const result = await sendEmail(bankingEmail, subject, content);
        results.banking = {
          success: result.success,
          messageId: result.messageId,
          to: result.to,
          email: bankingEmail,
          subject,
          content,
          status: result.success ? 'sent' : 'failed',
          error: result.error
        };
      } catch (error) {
        console.error('❌ Banking email error:', error);
        results.banking = { success: false, error: error.message, status: 'failed', subject, content };
      }
    }

    // Send to nodal officer
    if (recipients.nodal) {
      const template = emailTemplates.nodal;
      const subject = template.subject;
      const content = template.template(caseData, scammerData);
      console.log('📧 Sending email to nodal:', nodalEmail);
      try {
        const result = await sendEmail(nodalEmail, subject, content);
        results.nodal = {
          success: result.success,
          messageId: result.messageId,
          to: result.to,
          email: nodalEmail,
          subject,
          content,
          status: result.success ? 'sent' : 'failed',
          error: result.error
        };
      } catch (error) {
        console.error('❌ Nodal email error:', error);
        results.nodal = { success: false, error: error.message, status: 'failed', subject, content };
      }
    }

    return results;
  } catch (error) {
    console.error('Error in sendEmailsToAuthorities:', error);
    throw error;
  }
}

// Test email configuration
async function testEmailConfiguration() {
  try {
    await transporter.verify();
    console.log('✅ Email configuration is valid');
    return true;
  } catch (error) {
    console.error('❌ Email configuration is invalid:', error);
    return false;
  }
}

module.exports = {
  sendEmail,
  sendEmailsToAuthorities,
  testEmailConfiguration,
  emailTemplates
};
